[phases.setup]
aptPkgs = ["ffmpeg", "libsndfile1"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "mkdir -p model_vosk_ru",
  "wget -q https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip",
  "unzip -q vosk-model-small-ru-0.22.zip -d model_vosk_ru",
  "rm vosk-model-small-ru-0.22.zip"
]
